int L_Count;
#define L_CountString "L_Count"
int L_Selected;
#define L_SelectedString "L_Selected"
int L_Comment;
#define L_CommentString "L_Comment"
int L_GUID;
#define L_GUIDString "L_GUID"
int L_Name;
#define L_NameString "L_Name"
int L_TimeStamp;
#define L_TimeStampString "L_TimeStamp"
int L_Select;
#define L_SelectString "L_Select"
int L_Comment_1;
#define L_Comment_1String "L_Comment_1"
int L_GUID_1;
#define L_GUID_1String "L_GUID_1"
int L_Name_1;
#define L_Name_1String "L_Name_1"
int L_TimeStamp_1;
#define L_TimeStamp_1String "L_TimeStamp_1"
int L_Select_1;
#define L_Select_1String "L_Select_1"
int L_Comment_2;
#define L_Comment_2String "L_Comment_2"
int L_GUID_2;
#define L_GUID_2String "L_GUID_2"
int L_Name_2;
#define L_Name_2String "L_Name_2"
int L_TimeStamp_2;
#define L_TimeStamp_2String "L_TimeStamp_2"
int L_Select_2;
#define L_Select_2String "L_Select_2"
int L_Comment_3;
#define L_Comment_3String "L_Comment_3"
int L_GUID_3;
#define L_GUID_3String "L_GUID_3"
int L_Name_3;
#define L_Name_3String "L_Name_3"
int L_TimeStamp_3;
#define L_TimeStamp_3String "L_TimeStamp_3"
int L_Select_3;
#define L_Select_3String "L_Select_3"
int L_Comment_4;
#define L_Comment_4String "L_Comment_4"
int L_GUID_4;
#define L_GUID_4String "L_GUID_4"
int L_Name_4;
#define L_Name_4String "L_Name_4"
int L_TimeStamp_4;
#define L_TimeStamp_4String "L_TimeStamp_4"
int L_Select_4;
#define L_Select_4String "L_Select_4"
int L_Comment_5;
#define L_Comment_5String "L_Comment_5"
int L_GUID_5;
#define L_GUID_5String "L_GUID_5"
int L_Name_5;
#define L_Name_5String "L_Name_5"
int L_TimeStamp_5;
#define L_TimeStamp_5String "L_TimeStamp_5"
int L_Select_5;
#define L_Select_5String "L_Select_5"
int L_isFace1;
#define L_isFace1String "L_isFace1"
int L_Value;
#define L_ValueString "L_Value"
int L_Change;
#define L_ChangeString "L_Change"
int L_StartBubbleReadoutStream;
#define L_StartBubbleReadoutStreamString "L_StartBubbleReadoutStream"
int L_StopBubbleReadoutStream;
#define L_StopBubbleReadoutStreamString "L_StopBubbleReadoutStream"
int L_Label;
#define L_LabelString "L_Label"
int L_Value_1;
#define L_Value_1String "L_Value_1"
int L_ThresholdExceededTimel;
#define L_ThresholdExceededTimelString "L_ThresholdExceededTimel"
int L_WorkingRangeExceededTime;
#define L_WorkingRangeExceededTimeString "L_WorkingRangeExceededTime"
int L_Label_1;
#define L_Label_1String "L_Label_1"
int L_Value_2;
#define L_Value_2String "L_Value_2"
int L_TimeStamp_6;
#define L_TimeStamp_6String "L_TimeStamp_6"
int L_Label_2;
#define L_Label_2String "L_Label_2"
int L_UnitString;
#define L_UnitStringString "L_UnitString"
int L_UnitType;
#define L_UnitTypeString "L_UnitType"
int L_Value_3;
#define L_Value_3String "L_Value_3"
int L_ValueInBaseUnits;
#define L_ValueInBaseUnitsString "L_ValueInBaseUnits"
int L_Label_3;
#define L_Label_3String "L_Label_3"
int L_UnitString_1;
#define L_UnitString_1String "L_UnitString_1"
int L_UnitType_1;
#define L_UnitType_1String "L_UnitType_1"
int L_Value_4;
#define L_Value_4String "L_Value_4"
int L_ValueInBaseUnits_1;
#define L_ValueInBaseUnits_1String "L_ValueInBaseUnits_1"
int L_Label_4;
#define L_Label_4String "L_Label_4"
int L_UnitString_2;
#define L_UnitString_2String "L_UnitString_2"
int L_UnitType_2;
#define L_UnitType_2String "L_UnitType_2"
int L_Value_5;
#define L_Value_5String "L_Value_5"
int L_ValueInBaseUnits_2;
#define L_ValueInBaseUnits_2String "L_ValueInBaseUnits_2"
int L_Label_5;
#define L_Label_5String "L_Label_5"
int L_UnitString_3;
#define L_UnitString_3String "L_UnitString_3"
int L_UnitType_3;
#define L_UnitType_3String "L_UnitType_3"
int L_Value_6;
#define L_Value_6String "L_Value_6"
int L_ValueInBaseUnits_3;
#define L_ValueInBaseUnits_3String "L_ValueInBaseUnits_3"
int L_Label_6;
#define L_Label_6String "L_Label_6"
int L_Value_7;
#define L_Value_7String "L_Value_7"
int L_Label_7;
#define L_Label_7String "L_Label_7"
int L_Value_8;
#define L_Value_8String "L_Value_8"
int L_Reset;
#define L_ResetString "L_Reset"
int L_GetInclinationToGravity;
#define L_GetInclinationToGravityString "L_GetInclinationToGravity"
int L_GetInclinationToGravityAsync;
#define L_GetInclinationToGravityAsyncString "L_GetInclinationToGravityAsync"
int L_Measure;
#define L_MeasureString "L_Measure"
int L_WakeUpTime;
#define L_WakeUpTimeString "L_WakeUpTime"
int L_Label_8;
#define L_Label_8String "L_Label_8"
int L_IsWarmValue;
#define L_IsWarmValueString "L_IsWarmValue"
int L_Label_9;
#define L_Label_9String "L_Label_9"
int L_IsOnValue;
#define L_IsOnValueString "L_IsOnValue"
int L_GoToSleep;
#define L_GoToSleepString "L_GoToSleep"
int L_Label_10;
#define L_Label_10String "L_Label_10"
int L_Value_9;
#define L_Value_9String "L_Value_9"
int L_Count_1;
#define L_Count_1String "L_Count_1"
int L_GUID_6;
#define L_GUID_6String "L_GUID_6"
int L_Name_6;
#define L_Name_6String "L_Name_6"
int L_Label_11;
#define L_Label_11String "L_Label_11"
int L_Value_10;
#define L_Value_10String "L_Value_10"
int L_Label_12;
#define L_Label_12String "L_Label_12"
int L_Value_11;
#define L_Value_11String "L_Value_11"
int L_Select_6;
#define L_Select_6String "L_Select_6"
int L_GUID_7;
#define L_GUID_7String "L_GUID_7"
int L_Name_7;
#define L_Name_7String "L_Name_7"
int L_Label_13;
#define L_Label_13String "L_Label_13"
int L_MaxValue;
#define L_MaxValueString "L_MaxValue"
int L_MaxValueInBaseUnits;
#define L_MaxValueInBaseUnitsString "L_MaxValueInBaseUnits"
int L_MinValue;
#define L_MinValueString "L_MinValue"
int L_MinValueInBaseUnits;
#define L_MinValueInBaseUnitsString "L_MinValueInBaseUnits"
int L_UnitString_4;
#define L_UnitString_4String "L_UnitString_4"
int L_UnitType_4;
#define L_UnitType_4String "L_UnitType_4"
int L_Value_12;
#define L_Value_12String "L_Value_12"
int L_ValueInBaseUnits_4;
#define L_ValueInBaseUnits_4String "L_ValueInBaseUnits_4"
int L_Label_14;
#define L_Label_14String "L_Label_14"
int L_MaxValue_1;
#define L_MaxValue_1String "L_MaxValue_1"
int L_MaxValueInBaseUnits_1;
#define L_MaxValueInBaseUnits_1String "L_MaxValueInBaseUnits_1"
int L_MinValue_1;
#define L_MinValue_1String "L_MinValue_1"
int L_MinValueInBaseUnits_1;
#define L_MinValueInBaseUnits_1String "L_MinValueInBaseUnits_1"
int L_UnitString_5;
#define L_UnitString_5String "L_UnitString_5"
int L_UnitType_5;
#define L_UnitType_5String "L_UnitType_5"
int L_Value_13;
#define L_Value_13String "L_Value_13"
int L_ValueInBaseUnits_5;
#define L_ValueInBaseUnits_5String "L_ValueInBaseUnits_5"
int L_Select_7;
#define L_Select_7String "L_Select_7"
int L_GUID_8;
#define L_GUID_8String "L_GUID_8"
int L_Name_8;
#define L_Name_8String "L_Name_8"
int L_Label_15;
#define L_Label_15String "L_Label_15"
int L_MaxValue_2;
#define L_MaxValue_2String "L_MaxValue_2"
int L_MaxValueInBaseUnits_2;
#define L_MaxValueInBaseUnits_2String "L_MaxValueInBaseUnits_2"
int L_MinValue_2;
#define L_MinValue_2String "L_MinValue_2"
int L_MinValueInBaseUnits_2;
#define L_MinValueInBaseUnits_2String "L_MinValueInBaseUnits_2"
int L_UnitString_6;
#define L_UnitString_6String "L_UnitString_6"
int L_UnitType_6;
#define L_UnitType_6String "L_UnitType_6"
int L_Value_14;
#define L_Value_14String "L_Value_14"
int L_ValueInBaseUnits_6;
#define L_ValueInBaseUnits_6String "L_ValueInBaseUnits_6"
int L_Select_8;
#define L_Select_8String "L_Select_8"
int L_GUID_9;
#define L_GUID_9String "L_GUID_9"
int L_Name_9;
#define L_Name_9String "L_Name_9"
int L_Label_16;
#define L_Label_16String "L_Label_16"
int L_Value_15;
#define L_Value_15String "L_Value_15"
int L_Label_17;
#define L_Label_17String "L_Label_17"
int L_Value_16;
#define L_Value_16String "L_Value_16"
int L_Label_18;
#define L_Label_18String "L_Label_18"
int L_MaxValue_3;
#define L_MaxValue_3String "L_MaxValue_3"
int L_MaxValueInBaseUnits_3;
#define L_MaxValueInBaseUnits_3String "L_MaxValueInBaseUnits_3"
int L_MinValue_3;
#define L_MinValue_3String "L_MinValue_3"
int L_MinValueInBaseUnits_3;
#define L_MinValueInBaseUnits_3String "L_MinValueInBaseUnits_3"
int L_UnitString_7;
#define L_UnitString_7String "L_UnitString_7"
int L_UnitType_7;
#define L_UnitType_7String "L_UnitType_7"
int L_Value_17;
#define L_Value_17String "L_Value_17"
int L_ValueInBaseUnits_7;
#define L_ValueInBaseUnits_7String "L_ValueInBaseUnits_7"
int L_Label_19;
#define L_Label_19String "L_Label_19"
int L_MaxValue_4;
#define L_MaxValue_4String "L_MaxValue_4"
int L_MaxValueInBaseUnits_4;
#define L_MaxValueInBaseUnits_4String "L_MaxValueInBaseUnits_4"
int L_MinValue_4;
#define L_MinValue_4String "L_MinValue_4"
int L_MinValueInBaseUnits_4;
#define L_MinValueInBaseUnits_4String "L_MinValueInBaseUnits_4"
int L_UnitString_8;
#define L_UnitString_8String "L_UnitString_8"
int L_UnitType_8;
#define L_UnitType_8String "L_UnitType_8"
int L_Value_18;
#define L_Value_18String "L_Value_18"
int L_ValueInBaseUnits_8;
#define L_ValueInBaseUnits_8String "L_ValueInBaseUnits_8"
int L_Label_20;
#define L_Label_20String "L_Label_20"
int L_Value_19;
#define L_Value_19String "L_Value_19"
int L_Label_21;
#define L_Label_21String "L_Label_21"
int L_Value_20;
#define L_Value_20String "L_Value_20"
int L_Select_9;
#define L_Select_9String "L_Select_9"
int L_GUID_10;
#define L_GUID_10String "L_GUID_10"
int L_Name_10;
#define L_Name_10String "L_Name_10"
int L_Label_22;
#define L_Label_22String "L_Label_22"
int L_Value_21;
#define L_Value_21String "L_Value_21"
int L_Count_2;
#define L_Count_2String "L_Count_2"
int L_GetSnapShot;
#define L_GetSnapShotString "L_GetSnapShot"
int L_Description;
#define L_DescriptionString "L_Description"
int L_Number;
#define L_NumberString "L_Number"
int L_Solution;
#define L_SolutionString "L_Solution"
int L_Title;
#define L_TitleString "L_Title"
int L_Description_1;
#define L_Description_1String "L_Description_1"
int L_Number_1;
#define L_Number_1String "L_Number_1"
int L_Solution_1;
#define L_Solution_1String "L_Solution_1"
int L_Title_1;
#define L_Title_1String "L_Title_1"
int L_Description_2;
#define L_Description_2String "L_Description_2"
int L_Number_2;
#define L_Number_2String "L_Number_2"
int L_Solution_2;
#define L_Solution_2String "L_Solution_2"
int L_Title_2;
#define L_Title_2String "L_Title_2"
int L_Description_3;
#define L_Description_3String "L_Description_3"
int L_Number_3;
#define L_Number_3String "L_Number_3"
int L_Solution_3;
#define L_Solution_3String "L_Solution_3"
int L_Title_3;
#define L_Title_3String "L_Title_3"
int L_Description_4;
#define L_Description_4String "L_Description_4"
int L_Number_4;
#define L_Number_4String "L_Number_4"
int L_Solution_4;
#define L_Solution_4String "L_Solution_4"
int L_Title_4;
#define L_Title_4String "L_Title_4"
int L_IsFixedSize;
#define L_IsFixedSizeString "L_IsFixedSize"
int L_IsReadOnly;
#define L_IsReadOnlyString "L_IsReadOnly"
int L_IsSynchronized;
#define L_IsSynchronizedString "L_IsSynchronized"
int L_Length;
#define L_LengthString "L_Length"
int L_LongLength;
#define L_LongLengthString "L_LongLength"
int L_Rank;
#define L_RankString "L_Rank"
int L_GoAndMeasureStationary;
#define L_GoAndMeasureStationaryString "L_GoAndMeasureStationary"
int L_lockOnTokenName;
#define L_lockOnTokenNameString "L_lockOnTokenName"
int L_IsRelative;
#define L_IsRelativeString "L_IsRelative"
int L_Pos1;
#define L_Pos1String "L_Pos1"
int L_Pos2;
#define L_Pos2String "L_Pos2"
int L_Pos3;
#define L_Pos3String "L_Pos3"
int L_GoAndMeasureStationaryAsync;
#define L_GoAndMeasureStationaryAsyncString "L_GoAndMeasureStationaryAsync"
int L_lockOnTokenName_1;
#define L_lockOnTokenName_1String "L_lockOnTokenName_1"
int L_IsRelative_1;
#define L_IsRelative_1String "L_IsRelative_1"
int L_Pos1_1;
#define L_Pos1_1String "L_Pos1_1"
int L_Pos2_1;
#define L_Pos2_1String "L_Pos2_1"
int L_Pos3_1;
#define L_Pos3_1String "L_Pos3_1"
int L_MeasureStationary;
#define L_MeasureStationaryString "L_MeasureStationary"
int L_StartMeasurement;
#define L_StartMeasurementString "L_StartMeasurement"
int L_StopMeasurement;
#define L_StopMeasurementString "L_StopMeasurement"
int L_Label_23;
#define L_Label_23String "L_Label_23"
int L_SerialNumber;
#define L_SerialNumberString "L_SerialNumber"
int L_UnitString_9;
#define L_UnitString_9String "L_UnitString_9"
int L_UnitType_9;
#define L_UnitType_9String "L_UnitType_9"
int L_HumidityValue;
#define L_HumidityValueString "L_HumidityValue"
int L_ValueInBaseUnits_9;
#define L_ValueInBaseUnits_9String "L_ValueInBaseUnits_9"
int L_Label_24;
#define L_Label_24String "L_Label_24"
int L_Value_22;
#define L_Value_22String "L_Value_22"
int L_Label_25;
#define L_Label_25String "L_Label_25"
int L_SerialNumber_1;
#define L_SerialNumber_1String "L_SerialNumber_1"
int L_UnitString_10;
#define L_UnitString_10String "L_UnitString_10"
int L_UnitType_10;
#define L_UnitType_10String "L_UnitType_10"
int L_PressureValue;
#define L_PressureValueString "L_PressureValue"
int L_ValueInBaseUnits_10;
#define L_ValueInBaseUnits_10String "L_ValueInBaseUnits_10"
int L_Label_26;
#define L_Label_26String "L_Label_26"
int L_Value_23;
#define L_Value_23String "L_Value_23"
int L_Label_27;
#define L_Label_27String "L_Label_27"
int L_SerialNumber_2;
#define L_SerialNumber_2String "L_SerialNumber_2"
int L_UnitString_11;
#define L_UnitString_11String "L_UnitString_11"
int L_UnitType_11;
#define L_UnitType_11String "L_UnitType_11"
int L_TemperatureValue;
#define L_TemperatureValueString "L_TemperatureValue"
int L_ValueInBaseUnits_11;
#define L_ValueInBaseUnits_11String "L_ValueInBaseUnits_11"
int L_Label_28;
#define L_Label_28String "L_Label_28"
int L_Value_24;
#define L_Value_24String "L_Value_24"
int L_Label_29;
#define L_Label_29String "L_Label_29"
int L_Value_25;
#define L_Value_25String "L_Value_25"
int L_Label_30;
#define L_Label_30String "L_Label_30"
int L_MaxValue_5;
#define L_MaxValue_5String "L_MaxValue_5"
int L_MaxValueInBaseUnits_5;
#define L_MaxValueInBaseUnits_5String "L_MaxValueInBaseUnits_5"
int L_MinValue_5;
#define L_MinValue_5String "L_MinValue_5"
int L_MinValueInBaseUnits_5;
#define L_MinValueInBaseUnits_5String "L_MinValueInBaseUnits_5"
int L_SerialNumber_3;
#define L_SerialNumber_3String "L_SerialNumber_3"
int L_UnitString_12;
#define L_UnitString_12String "L_UnitString_12"
int L_UnitType_12;
#define L_UnitType_12String "L_UnitType_12"
int L_MHumidityValue;
#define L_MHumidityValueString "L_MHumidityValue"
int L_ValueInBaseUnits_12;
#define L_ValueInBaseUnits_12String "L_ValueInBaseUnits_12"
int L_Label_31;
#define L_Label_31String "L_Label_31"
int L_MaxValue_6;
#define L_MaxValue_6String "L_MaxValue_6"
int L_MaxValueInBaseUnits_6;
#define L_MaxValueInBaseUnits_6String "L_MaxValueInBaseUnits_6"
int L_MinValue_6;
#define L_MinValue_6String "L_MinValue_6"
int L_MinValueInBaseUnits_6;
#define L_MinValueInBaseUnits_6String "L_MinValueInBaseUnits_6"
int L_SerialNumber_4;
#define L_SerialNumber_4String "L_SerialNumber_4"
int L_UnitString_13;
#define L_UnitString_13String "L_UnitString_13"
int L_UnitType_13;
#define L_UnitType_13String "L_UnitType_13"
int L_MPressureValue;
#define L_MPressureValueString "L_MPressureValue"
int L_ValueInBaseUnits_13;
#define L_ValueInBaseUnits_13String "L_ValueInBaseUnits_13"
int L_Label_32;
#define L_Label_32String "L_Label_32"
int L_MaxValue_7;
#define L_MaxValue_7String "L_MaxValue_7"
int L_MaxValueInBaseUnits_7;
#define L_MaxValueInBaseUnits_7String "L_MaxValueInBaseUnits_7"
int L_MinValue_7;
#define L_MinValue_7String "L_MinValue_7"
int L_MinValueInBaseUnits_7;
#define L_MinValueInBaseUnits_7String "L_MinValueInBaseUnits_7"
int L_SerialNumber_5;
#define L_SerialNumber_5String "L_SerialNumber_5"
int L_UnitString_14;
#define L_UnitString_14String "L_UnitString_14"
int L_UnitType_14;
#define L_UnitType_14String "L_UnitType_14"
int L_MTemperatureValue;
#define L_MTemperatureValueString "L_MTemperatureValue"
int L_ValueInBaseUnits_14;
#define L_ValueInBaseUnits_14String "L_ValueInBaseUnits_14"
int L_Label_33;
#define L_Label_33String "L_Label_33"
int L_SerialNumber_6;
#define L_SerialNumber_6String "L_SerialNumber_6"
int L_UnitString_15;
#define L_UnitString_15String "L_UnitString_15"
int L_UnitType_15;
#define L_UnitType_15String "L_UnitType_15"
int L_OTemperatureValue;
#define L_OTemperatureValueString "L_OTemperatureValue"
int L_ValueInBaseUnits_15;
#define L_ValueInBaseUnits_15String "L_ValueInBaseUnits_15"
int L_Label_34;
#define L_Label_34String "L_Label_34"
int L_Value_26;
#define L_Value_26String "L_Value_26"
int L_Label_35;
#define L_Label_35String "L_Label_35"
int L_Value_27;
#define L_Value_27String "L_Value_27"
int L_Label_36;
#define L_Label_36String "L_Label_36"
int L_MaxValue_8;
#define L_MaxValue_8String "L_MaxValue_8"
int L_MaxValueInBaseUnits_8;
#define L_MaxValueInBaseUnits_8String "L_MaxValueInBaseUnits_8"
int L_MinValue_8;
#define L_MinValue_8String "L_MinValue_8"
int L_MinValueInBaseUnits_8;
#define L_MinValueInBaseUnits_8String "L_MinValueInBaseUnits_8"
int L_UnitString_16;
#define L_UnitString_16String "L_UnitString_16"
int L_UnitType_16;
#define L_UnitType_16String "L_UnitType_16"
int L_Value_28;
#define L_Value_28String "L_Value_28"
int L_ValueInBaseUnits_16;
#define L_ValueInBaseUnits_16String "L_ValueInBaseUnits_16"
int L_Label_37;
#define L_Label_37String "L_Label_37"
int L_MaxValue_9;
#define L_MaxValue_9String "L_MaxValue_9"
int L_MaxValueInBaseUnits_9;
#define L_MaxValueInBaseUnits_9String "L_MaxValueInBaseUnits_9"
int L_MinValue_9;
#define L_MinValue_9String "L_MinValue_9"
int L_MinValueInBaseUnits_9;
#define L_MinValueInBaseUnits_9String "L_MinValueInBaseUnits_9"
int L_UnitString_17;
#define L_UnitString_17String "L_UnitString_17"
int L_UnitType_17;
#define L_UnitType_17String "L_UnitType_17"
int L_Value_29;
#define L_Value_29String "L_Value_29"
int L_ValueInBaseUnits_17;
#define L_ValueInBaseUnits_17String "L_ValueInBaseUnits_17"
int L_Close;
#define L_CloseString "L_Close"
int L_Show;
#define L_ShowString "L_Show"
int L_ShowDialog;
#define L_ShowDialogString "L_ShowDialog"
int L_ShowOnProcess;
#define L_ShowOnProcessString "L_ShowOnProcess"
int L_ShowTopmost;
#define L_ShowTopmostString "L_ShowTopmost"
int L_GetStillImage;
#define L_GetStillImageString "L_GetStillImage"
int L_MoveToPixel;
#define L_MoveToPixelString "L_MoveToPixel"
int L_StartAsync;
#define L_StartAsyncString "L_StartAsync"
int L_Stop;
#define L_StopString "L_Stop"
int L_Label_38;
#define L_Label_38String "L_Label_38"
int L_Value_30;
#define L_Value_30String "L_Value_30"
int L_GetTargetDirections;
#define L_GetTargetDirectionsString "L_GetTargetDirections"
int L_Label_39;
#define L_Label_39String "L_Label_39"
int L_UnitString_18;
#define L_UnitString_18String "L_UnitString_18"
int L_UnitType_18;
#define L_UnitType_18String "L_UnitType_18"
int L_Value_31;
#define L_Value_31String "L_Value_31"
int L_ValueInBaseUnits_18;
#define L_ValueInBaseUnits_18String "L_ValueInBaseUnits_18"
int L_Label_40;
#define L_Label_40String "L_Label_40"
int L_Value_32;
#define L_Value_32String "L_Value_32"
int L_Label_41;
#define L_Label_41String "L_Label_41"
int L_Value_33;
#define L_Value_33String "L_Value_33"
int L_CoordinateType;
#define L_CoordinateTypeString "L_CoordinateType"
int L_RotationType;
#define L_RotationTypeString "L_RotationType"
int L_AngleUnit;
#define L_AngleUnitString "L_AngleUnit"
int L_HumidityUnit;
#define L_HumidityUnitString "L_HumidityUnit"
int L_LengthUnit;
#define L_LengthUnitString "L_LengthUnit"
int L_PercentUnit;
#define L_PercentUnitString "L_PercentUnit"
int L_PressureUnit;
#define L_PressureUnitString "L_PressureUnit"
int L_TemperatureUnit;
#define L_TemperatureUnitString "L_TemperatureUnit"
int L_TimeUnit;
#define L_TimeUnitString "L_TimeUnit"
int L_AngleUnit_1;
#define L_AngleUnit_1String "L_AngleUnit_1"
int L_HumidityUnit_1;
#define L_HumidityUnit_1String "L_HumidityUnit_1"
int L_LengthUnit_1;
#define L_LengthUnit_1String "L_LengthUnit_1"
int L_PercentUnit_1;
#define L_PercentUnit_1String "L_PercentUnit_1"
int L_PressureUnit_1;
#define L_PressureUnit_1String "L_PressureUnit_1"
int L_TemperatureUnit_1;
#define L_TemperatureUnit_1String "L_TemperatureUnit_1"
int L_TimeUnit_1;
#define L_TimeUnit_1String "L_TimeUnit_1"
int L_GetOrientation;
#define L_GetOrientationString "L_GetOrientation"
int L_CoordinateType_1;
#define L_CoordinateType_1String "L_CoordinateType_1"
int L_RotationType_1;
#define L_RotationType_1String "L_RotationType_1"
int L_Label_42;
#define L_Label_42String "L_Label_42"
int L_UnitString_19;
#define L_UnitString_19String "L_UnitString_19"
int L_UnitType_19;
#define L_UnitType_19String "L_UnitType_19"
int L_Value_34;
#define L_Value_34String "L_Value_34"
int L_ValueInBaseUnits_19;
#define L_ValueInBaseUnits_19String "L_ValueInBaseUnits_19"
int L_Label_43;
#define L_Label_43String "L_Label_43"
int L_UnitString_20;
#define L_UnitString_20String "L_UnitString_20"
int L_UnitType_20;
#define L_UnitType_20String "L_UnitType_20"
int L_Value_35;
#define L_Value_35String "L_Value_35"
int L_ValueInBaseUnits_20;
#define L_ValueInBaseUnits_20String "L_ValueInBaseUnits_20"
int L_Label_44;
#define L_Label_44String "L_Label_44"
int L_UnitString_21;
#define L_UnitString_21String "L_UnitString_21"
int L_UnitType_21;
#define L_UnitType_21String "L_UnitType_21"
int L_Value_36;
#define L_Value_36String "L_Value_36"
int L_ValueInBaseUnits_21;
#define L_ValueInBaseUnits_21String "L_ValueInBaseUnits_21"
int L_Label_45;
#define L_Label_45String "L_Label_45"
int L_UnitString_22;
#define L_UnitString_22String "L_UnitString_22"
int L_UnitType_22;
#define L_UnitType_22String "L_UnitType_22"
int L_Value_37;
#define L_Value_37String "L_Value_37"
int L_ValueInBaseUnits_22;
#define L_ValueInBaseUnits_22String "L_ValueInBaseUnits_22"
int L_Label_46;
#define L_Label_46String "L_Label_46"
int L_UnitString_23;
#define L_UnitString_23String "L_UnitString_23"
int L_UnitType_23;
#define L_UnitType_23String "L_UnitType_23"
int L_Value_38;
#define L_Value_38String "L_Value_38"
int L_ValueInBaseUnits_23;
#define L_ValueInBaseUnits_23String "L_ValueInBaseUnits_23"
int L_Label_47;
#define L_Label_47String "L_Label_47"
int L_UnitString_24;
#define L_UnitString_24String "L_UnitString_24"
int L_UnitType_24;
#define L_UnitType_24String "L_UnitType_24"
int L_Value_39;
#define L_Value_39String "L_Value_39"
int L_ValueInBaseUnits_24;
#define L_ValueInBaseUnits_24String "L_ValueInBaseUnits_24"
int L_Label_48;
#define L_Label_48String "L_Label_48"
int L_UnitString_25;
#define L_UnitString_25String "L_UnitString_25"
int L_UnitType_25;
#define L_UnitType_25String "L_UnitType_25"
int L_Value_40;
#define L_Value_40String "L_Value_40"
int L_ValueInBaseUnits_25;
#define L_ValueInBaseUnits_25String "L_ValueInBaseUnits_25"
int L_GetTransformation;
#define L_GetTransformationString "L_GetTransformation"
int L_CoordinateType_2;
#define L_CoordinateType_2String "L_CoordinateType_2"
int L_RotationType_2;
#define L_RotationType_2String "L_RotationType_2"
int L_Label_49;
#define L_Label_49String "L_Label_49"
int L_UnitString_26;
#define L_UnitString_26String "L_UnitString_26"
int L_UnitType_26;
#define L_UnitType_26String "L_UnitType_26"
int L_Value_41;
#define L_Value_41String "L_Value_41"
int L_ValueInBaseUnits_26;
#define L_ValueInBaseUnits_26String "L_ValueInBaseUnits_26"
int L_Label_50;
#define L_Label_50String "L_Label_50"
int L_UnitString_27;
#define L_UnitString_27String "L_UnitString_27"
int L_UnitType_27;
#define L_UnitType_27String "L_UnitType_27"
int L_Value_42;
#define L_Value_42String "L_Value_42"
int L_ValueInBaseUnits_27;
#define L_ValueInBaseUnits_27String "L_ValueInBaseUnits_27"
int L_Label_51;
#define L_Label_51String "L_Label_51"
int L_UnitString_28;
#define L_UnitString_28String "L_UnitString_28"
int L_UnitType_28;
#define L_UnitType_28String "L_UnitType_28"
int L_Value_43;
#define L_Value_43String "L_Value_43"
int L_ValueInBaseUnits_28;
#define L_ValueInBaseUnits_28String "L_ValueInBaseUnits_28"
int L_Label_52;
#define L_Label_52String "L_Label_52"
int L_UnitString_29;
#define L_UnitString_29String "L_UnitString_29"
int L_UnitType_29;
#define L_UnitType_29String "L_UnitType_29"
int L_Value_44;
#define L_Value_44String "L_Value_44"
int L_ValueInBaseUnits_29;
#define L_ValueInBaseUnits_29String "L_ValueInBaseUnits_29"
int L_Label_53;
#define L_Label_53String "L_Label_53"
int L_UnitString_30;
#define L_UnitString_30String "L_UnitString_30"
int L_UnitType_30;
#define L_UnitType_30String "L_UnitType_30"
int L_Value_45;
#define L_Value_45String "L_Value_45"
int L_ValueInBaseUnits_30;
#define L_ValueInBaseUnits_30String "L_ValueInBaseUnits_30"
int L_Label_54;
#define L_Label_54String "L_Label_54"
int L_UnitString_31;
#define L_UnitString_31String "L_UnitString_31"
int L_UnitType_31;
#define L_UnitType_31String "L_UnitType_31"
int L_Value_46;
#define L_Value_46String "L_Value_46"
int L_ValueInBaseUnits_31;
#define L_ValueInBaseUnits_31String "L_ValueInBaseUnits_31"
int L_Label_55;
#define L_Label_55String "L_Label_55"
int L_UnitString_32;
#define L_UnitString_32String "L_UnitString_32"
int L_UnitType_32;
#define L_UnitType_32String "L_UnitType_32"
int L_Value_47;
#define L_Value_47String "L_Value_47"
int L_ValueInBaseUnits_32;
#define L_ValueInBaseUnits_32String "L_ValueInBaseUnits_32"
int L_Label_56;
#define L_Label_56String "L_Label_56"
int L_UnitString_33;
#define L_UnitString_33String "L_UnitString_33"
int L_UnitType_33;
#define L_UnitType_33String "L_UnitType_33"
int L_Value_48;
#define L_Value_48String "L_Value_48"
int L_ValueInBaseUnits_33;
#define L_ValueInBaseUnits_33String "L_ValueInBaseUnits_33"
int L_SetCalculatedOrientation;
#define L_SetCalculatedOrientationString "L_SetCalculatedOrientation"
int L_RMS;
#define L_RMSString "L_RMS"
int L_SetCalulatedTransformation;
#define L_SetCalulatedTransformationString "L_SetCalulatedTransformation"
int L_RMS_1;
#define L_RMS_1String "L_RMS_1"
int L_SetOrientation;
#define L_SetOrientationString "L_SetOrientation"
int L_ParamTranslation1;
#define L_ParamTranslation1String "L_ParamTranslation1"
int L_ParamTranslation2;
#define L_ParamTranslation2String "L_ParamTranslation2"
int L_ParamTranslation3;
#define L_ParamTranslation3String "L_ParamTranslation3"
int L_ParamRotation1;
#define L_ParamRotation1String "L_ParamRotation1"
int L_ParamRotation2;
#define L_ParamRotation2String "L_ParamRotation2"
int L_ParamRotation3;
#define L_ParamRotation3String "L_ParamRotation3"
int L_ParamRotation4;
#define L_ParamRotation4String "L_ParamRotation4"
int L_SetTransformation;
#define L_SetTransformationString "L_SetTransformation"
int L_ParamTranslation1_1;
#define L_ParamTranslation1_1String "L_ParamTranslation1_1"
int L_ParamTranslation2_1;
#define L_ParamTranslation2_1String "L_ParamTranslation2_1"
int L_ParamTranslation3_1;
#define L_ParamTranslation3_1String "L_ParamTranslation3_1"
int L_ParamRotation1_1;
#define L_ParamRotation1_1String "L_ParamRotation1_1"
int L_ParamRotation2_1;
#define L_ParamRotation2_1String "L_ParamRotation2_1"
int L_ParamRotation3_1;
#define L_ParamRotation3_1String "L_ParamRotation3_1"
int L_ParamRotation4_1;
#define L_ParamRotation4_1String "L_ParamRotation4_1"
int L_paramScale;
#define L_paramScaleString "L_paramScale"
int L_Count_3;
#define L_Count_3String "L_Count_3"
int L_CreateLockOnToken;
#define L_CreateLockOnTokenString "L_CreateLockOnToken"
int L_paramTarget;
#define L_paramTargetString "L_paramTarget"
int L_faceNumber;
#define L_faceNumberString "L_faceNumber"
int L_Comment_6;
#define L_Comment_6String "L_Comment_6"
int L_GUID_11;
#define L_GUID_11String "L_GUID_11"
int L_IsSelectable;
#define L_IsSelectableString "L_IsSelectable"
int L_Name_11;
#define L_Name_11String "L_Name_11"
int L_ProductName;
#define L_ProductNameString "L_ProductName"
int L_TimeStamp_7;
#define L_TimeStamp_7String "L_TimeStamp_7"
int L_Label_57;
#define L_Label_57String "L_Label_57"
int L_UnitString_34;
#define L_UnitString_34String "L_UnitString_34"
int L_UnitType_34;
#define L_UnitType_34String "L_UnitType_34"
int L_Value_49;
#define L_Value_49String "L_Value_49"
int L_ValueInBaseUnits_34;
#define L_ValueInBaseUnits_34String "L_ValueInBaseUnits_34"
int L_Label_58;
#define L_Label_58String "L_Label_58"
int L_UnitString_35;
#define L_UnitString_35String "L_UnitString_35"
int L_UnitType_35;
#define L_UnitType_35String "L_UnitType_35"
int L_Value_50;
#define L_Value_50String "L_Value_50"
int L_ValueInBaseUnits_35;
#define L_ValueInBaseUnits_35String "L_ValueInBaseUnits_35"
int L_GetLockOnToken;
#define L_GetLockOnTokenString "L_GetLockOnToken"
int L_Select_10;
#define L_Select_10String "L_Select_10"
int L_Comment_7;
#define L_Comment_7String "L_Comment_7"
int L_GUID_12;
#define L_GUID_12String "L_GUID_12"
int L_IsSelectable_1;
#define L_IsSelectable_1String "L_IsSelectable_1"
int L_Name_12;
#define L_Name_12String "L_Name_12"
int L_ProductName_1;
#define L_ProductName_1String "L_ProductName_1"
int L_TimeStamp_8;
#define L_TimeStamp_8String "L_TimeStamp_8"
int L_Label_59;
#define L_Label_59String "L_Label_59"
int L_UnitString_36;
#define L_UnitString_36String "L_UnitString_36"
int L_UnitType_36;
#define L_UnitType_36String "L_UnitType_36"
int L_Value_51;
#define L_Value_51String "L_Value_51"
int L_ValueInBaseUnits_36;
#define L_ValueInBaseUnits_36String "L_ValueInBaseUnits_36"
int L_Label_60;
#define L_Label_60String "L_Label_60"
int L_UnitString_37;
#define L_UnitString_37String "L_UnitString_37"
int L_UnitType_37;
#define L_UnitType_37String "L_UnitType_37"
int L_Value_52;
#define L_Value_52String "L_Value_52"
int L_ValueInBaseUnits_37;
#define L_ValueInBaseUnits_37String "L_ValueInBaseUnits_37"
int L_GetLockOnToken_1;
#define L_GetLockOnToken_1String "L_GetLockOnToken_1"
int L_Select_11;
#define L_Select_11String "L_Select_11"
int L_Comment_8;
#define L_Comment_8String "L_Comment_8"
int L_GUID_13;
#define L_GUID_13String "L_GUID_13"
int L_IsSelectable_2;
#define L_IsSelectable_2String "L_IsSelectable_2"
int L_Name_13;
#define L_Name_13String "L_Name_13"
int L_ProductName_2;
#define L_ProductName_2String "L_ProductName_2"
int L_TimeStamp_9;
#define L_TimeStamp_9String "L_TimeStamp_9"
int L_Label_61;
#define L_Label_61String "L_Label_61"
int L_UnitString_38;
#define L_UnitString_38String "L_UnitString_38"
int L_UnitType_38;
#define L_UnitType_38String "L_UnitType_38"
int L_Value_53;
#define L_Value_53String "L_Value_53"
int L_ValueInBaseUnits_38;
#define L_ValueInBaseUnits_38String "L_ValueInBaseUnits_38"
int L_Label_62;
#define L_Label_62String "L_Label_62"
int L_UnitString_39;
#define L_UnitString_39String "L_UnitString_39"
int L_UnitType_39;
#define L_UnitType_39String "L_UnitType_39"
int L_Value_54;
#define L_Value_54String "L_Value_54"
int L_ValueInBaseUnits_39;
#define L_ValueInBaseUnits_39String "L_ValueInBaseUnits_39"
int L_GetLockOnToken_2;
#define L_GetLockOnToken_2String "L_GetLockOnToken_2"
int L_Select_12;
#define L_Select_12String "L_Select_12"
int L_Label_63;
#define L_Label_63String "L_Label_63"
int L_MaxValue_10;
#define L_MaxValue_10String "L_MaxValue_10"
int L_MaxValueInBaseUnits_10;
#define L_MaxValueInBaseUnits_10String "L_MaxValueInBaseUnits_10"
int L_MinValue_10;
#define L_MinValue_10String "L_MinValue_10"
int L_MinValueInBaseUnits_10;
#define L_MinValueInBaseUnits_10String "L_MinValueInBaseUnits_10"
int L_UnitString_40;
#define L_UnitString_40String "L_UnitString_40"
int L_UnitType_40;
#define L_UnitType_40String "L_UnitType_40"
int L_Value_55;
#define L_Value_55String "L_Value_55"
int L_ValueInBaseUnits_40;
#define L_ValueInBaseUnits_40String "L_ValueInBaseUnits_40"
int L_Label_64;
#define L_Label_64String "L_Label_64"
int L_MaxValue_11;
#define L_MaxValue_11String "L_MaxValue_11"
int L_MaxValueInBaseUnits_11;
#define L_MaxValueInBaseUnits_11String "L_MaxValueInBaseUnits_11"
int L_MinValue_11;
#define L_MinValue_11String "L_MinValue_11"
int L_MinValueInBaseUnits_11;
#define L_MinValueInBaseUnits_11String "L_MinValueInBaseUnits_11"
int L_UnitString_41;
#define L_UnitString_41String "L_UnitString_41"
int L_UnitType_41;
#define L_UnitType_41String "L_UnitType_41"
int L_Value_56;
#define L_Value_56String "L_Value_56"
int L_ValueInBaseUnits_41;
#define L_ValueInBaseUnits_41String "L_ValueInBaseUnits_41"
int L_Label_65;
#define L_Label_65String "L_Label_65"
int L_MaxValue_12;
#define L_MaxValue_12String "L_MaxValue_12"
int L_MaxValueInBaseUnits_12;
#define L_MaxValueInBaseUnits_12String "L_MaxValueInBaseUnits_12"
int L_MinValue_12;
#define L_MinValue_12String "L_MinValue_12"
int L_MinValueInBaseUnits_12;
#define L_MinValueInBaseUnits_12String "L_MinValueInBaseUnits_12"
int L_UnitString_42;
#define L_UnitString_42String "L_UnitString_42"
int L_UnitType_42;
#define L_UnitType_42String "L_UnitType_42"
int L_Value_57;
#define L_Value_57String "L_Value_57"
int L_ValueInBaseUnits_42;
#define L_ValueInBaseUnits_42String "L_ValueInBaseUnits_42"
int L_Start;
#define L_StartString "L_Start"
int L_StartAsync_1;
#define L_StartAsync_1String "L_StartAsync_1"
int L_Stop_1;
#define L_Stop_1String "L_Stop_1"
int L_Count_4;
#define L_Count_4String "L_Count_4"
int L_GUID_14;
#define L_GUID_14String "L_GUID_14"
int L_Name_14;
#define L_Name_14String "L_Name_14"
int L_Label_66;
#define L_Label_66String "L_Label_66"
int L_Value_58;
#define L_Value_58String "L_Value_58"
int L_Label_67;
#define L_Label_67String "L_Label_67"
int L_MaxValue_13;
#define L_MaxValue_13String "L_MaxValue_13"
int L_MaxValueInBaseUnits_13;
#define L_MaxValueInBaseUnits_13String "L_MaxValueInBaseUnits_13"
int L_MinValue_13;
#define L_MinValue_13String "L_MinValue_13"
int L_MinValueInBaseUnits_13;
#define L_MinValueInBaseUnits_13String "L_MinValueInBaseUnits_13"
int L_UnitString_43;
#define L_UnitString_43String "L_UnitString_43"
int L_UnitType_43;
#define L_UnitType_43String "L_UnitType_43"
int L_Value_59;
#define L_Value_59String "L_Value_59"
int L_ValueInBaseUnits_43;
#define L_ValueInBaseUnits_43String "L_ValueInBaseUnits_43"
int L_Label_68;
#define L_Label_68String "L_Label_68"
int L_MaxValue_14;
#define L_MaxValue_14String "L_MaxValue_14"
int L_MaxValueInBaseUnits_14;
#define L_MaxValueInBaseUnits_14String "L_MaxValueInBaseUnits_14"
int L_MinValue_14;
#define L_MinValue_14String "L_MinValue_14"
int L_MinValueInBaseUnits_14;
#define L_MinValueInBaseUnits_14String "L_MinValueInBaseUnits_14"
int L_UnitString_44;
#define L_UnitString_44String "L_UnitString_44"
int L_UnitType_44;
#define L_UnitType_44String "L_UnitType_44"
int L_Value_60;
#define L_Value_60String "L_Value_60"
int L_ValueInBaseUnits_44;
#define L_ValueInBaseUnits_44String "L_ValueInBaseUnits_44"
int L_Count_5;
#define L_Count_5String "L_Count_5"
int L_x00;
#define L_x00String "L_x00"
int L_y00;
#define L_y00String "L_y00"
int L_z00;
#define L_z00String "L_z00"
int L_GotoXYZ;
#define L_GotoXYZString "L_GotoXYZ"
int L_Targets;
#define L_TargetsString "L_Targets"
int L_x1;
#define L_x1String "L_x1"
int L_y1;
#define L_y1String "L_y1"
int L_GotoHere;
#define L_GotoHereString "L_GotoHere"
int L_x2;
#define L_x2String "L_x2"
int L_y2;
#define L_y2String "L_y2"
int L_GotoHere_1;
#define L_GotoHere_1String "L_GotoHere_1"
int L_x3;
#define L_x3String "L_x3"
int L_y3;
#define L_y3String "L_y3"
int L_GotoHere_2;
#define L_GotoHere_2String "L_GotoHere_2"
int L_x4;
#define L_x4String "L_x4"
int L_y4;
#define L_y4String "L_y4"
int L_GotoHere_3;
#define L_GotoHere_3String "L_GotoHere_3"
int L_x5;
#define L_x5String "L_x5"
int L_y5;
#define L_y5String "L_y5"
int L_GotoHere_4;
#define L_GotoHere_4String "L_GotoHere_4"
int L_x6;
#define L_x6String "L_x6"
int L_y6;
#define L_y6String "L_y6"
int L_GotoHere_5;
#define L_GotoHere_5String "L_GotoHere_5"
int L_XX;
#define L_XXString "L_XX"
int L_YY;
#define L_YYString "L_YY"
int L_GotoXY;
#define L_GotoXYString "L_GotoXY"
int L_x;
#define L_xString "L_x"
int L_y;
#define L_yString "L_y"
int L_z;
#define L_zString "L_z"
int L_x0;
#define L_x0String "L_x0"
int L_y0;
#define L_y0String "L_y0"
int L_z0;
#define L_z0String "L_z0"
int L_h;
#define L_hString "L_h"
int L_v;
#define L_vString "L_v"
int L_d;
#define L_dString "L_d"
int L_Topcomment;
#define L_TopcommentString "L_Topcomment"
int L_expectedFirmware;
#define L_expectedFirmwareString "L_expectedFirmware"
int L_installedFirmware;
#define L_installedFirmwareString "L_installedFirmware"
int L_ipAddress;
#define L_ipAddressString "L_ipAddress"
int L_IsCompatible;
#define L_IsCompatibleString "L_IsCompatible"
int L_Name_15;
#define L_Name_15String "L_Name_15"
int L_ProductName_3;
#define L_ProductName_3String "L_ProductName_3"
int L_SerialNumber_7;
#define L_SerialNumber_7String "L_SerialNumber_7"
int L_horizontalAngle;
#define L_horizontalAngleString "L_horizontalAngle"
int L_verticalAngle;
#define L_verticalAngleString "L_verticalAngle"
int L_angleUnits;
#define L_angleUnitsString "L_angleUnits"
int L_Disconnect;
#define L_DisconnectString "L_Disconnect"
int L_Dispose;
#define L_DisposeString "L_Dispose"
int L_GenerateLFile;
#define L_GenerateLFileString "L_GenerateLFile"
int L_ReturnValue;
#define L_ReturnValueString "L_ReturnValue"
int L_GetDirection;
#define L_GetDirectionString "L_GetDirection"
int L_TimeStamp_10;
#define L_TimeStamp_10String "L_TimeStamp_10"
int L_Label_69;
#define L_Label_69String "L_Label_69"
int L_UnitString_45;
#define L_UnitString_45String "L_UnitString_45"
int L_UnitType_45;
#define L_UnitType_45String "L_UnitType_45"
int L_Value_61;
#define L_Value_61String "L_Value_61"
int L_ValueInBaseUnits_45;
#define L_ValueInBaseUnits_45String "L_ValueInBaseUnits_45"
int L_Label_70;
#define L_Label_70String "L_Label_70"
int L_UnitString_46;
#define L_UnitString_46String "L_UnitString_46"
int L_UnitType_46;
#define L_UnitType_46String "L_UnitType_46"
int L_Value_62;
#define L_Value_62String "L_Value_62"
int L_ValueInBaseUnits_46;
#define L_ValueInBaseUnits_46String "L_ValueInBaseUnits_46"
int L_GetErrorDescription;
#define L_GetErrorDescriptionString "L_GetErrorDescription"
int L_ParamErrorNumber;
#define L_ParamErrorNumberString "L_ParamErrorNumber"
int L_Description_5;
#define L_Description_5String "L_Description_5"
int L_Number_5;
#define L_Number_5String "L_Number_5"
int L_Solution_5;
#define L_Solution_5String "L_Solution_5"
int L_Title_5;
#define L_Title_5String "L_Title_5"
int L_GetPrismPosition;
#define L_GetPrismPositionString "L_GetPrismPosition"
int L_MeasurementProfile;
#define L_MeasurementProfileString "L_MeasurementProfile"
int L_TimeStamp_11;
#define L_TimeStamp_11String "L_TimeStamp_11"
int L_Label_71;
#define L_Label_71String "L_Label_71"
int L_UnitString_47;
#define L_UnitString_47String "L_UnitString_47"
int L_UnitType_47;
#define L_UnitType_47String "L_UnitType_47"
int L_Value_63;
#define L_Value_63String "L_Value_63"
int L_ValueInBaseUnits_47;
#define L_ValueInBaseUnits_47String "L_ValueInBaseUnits_47"
int L_CoordinateType_3;
#define L_CoordinateType_3String "L_CoordinateType_3"
int L_isFace2;
#define L_isFace2String "L_isFace2"
int L_Label_72;
#define L_Label_72String "L_Label_72"
int L_UnitString_48;
#define L_UnitString_48String "L_UnitString_48"
int L_UnitType_48;
#define L_UnitType_48String "L_UnitType_48"
int L_Value_64;
#define L_Value_64String "L_Value_64"
int L_ValueInBaseUnits_48;
#define L_ValueInBaseUnits_48String "L_ValueInBaseUnits_48"
int L_Label_73;
#define L_Label_73String "L_Label_73"
int L_UnitString_49;
#define L_UnitString_49String "L_UnitString_49"
int L_UnitType_49;
#define L_UnitType_49String "L_UnitType_49"
int L_Value_65;
#define L_Value_65String "L_Value_65"
int L_ValueInBaseUnits_49;
#define L_ValueInBaseUnits_49String "L_ValueInBaseUnits_49"
int L_Label_74;
#define L_Label_74String "L_Label_74"
int L_UnitString_50;
#define L_UnitString_50String "L_UnitString_50"
int L_UnitType_50;
#define L_UnitType_50String "L_UnitType_50"
int L_Value_66;
#define L_Value_66String "L_Value_66"
int L_ValueInBaseUnits_50;
#define L_ValueInBaseUnits_50String "L_ValueInBaseUnits_50"
int L_Label_75;
#define L_Label_75String "L_Label_75"
int L_UnitString_51;
#define L_UnitString_51String "L_UnitString_51"
int L_UnitType_51;
#define L_UnitType_51String "L_UnitType_51"
int L_Value_67;
#define L_Value_67String "L_Value_67"
int L_ValueInBaseUnits_51;
#define L_ValueInBaseUnits_51String "L_ValueInBaseUnits_51"
int L_Label_76;
#define L_Label_76String "L_Label_76"
int L_UnitString_52;
#define L_UnitString_52String "L_UnitString_52"
int L_UnitType_52;
#define L_UnitType_52String "L_UnitType_52"
int L_Value_68;
#define L_Value_68String "L_Value_68"
int L_ValueInBaseUnits_52;
#define L_ValueInBaseUnits_52String "L_ValueInBaseUnits_52"
int L_GoHomePosition;
#define L_GoHomePositionString "L_GoHomePosition"
int L_Initialize;
#define L_InitializeString "L_Initialize"
int L_Move;
#define L_MoveString "L_Move"
int L_PercentageSpeedH;
#define L_PercentageSpeedHString "L_PercentageSpeedH"
int L_PercentageSpeedV;
#define L_PercentageSpeedVString "L_PercentageSpeedV"
int L_OpenTrackerScope;
#define L_OpenTrackerScopeString "L_OpenTrackerScope"
int L_PositionTo;
#define L_PositionToString "L_PositionTo"
int L_searchTarget;
#define L_searchTargetString "L_searchTarget"
int L_isRelative_2;
#define L_isRelative_2String "L_isRelative_2"
int L_Pos1_2;
#define L_Pos1_2String "L_Pos1_2"
int L_Pos2_2;
#define L_Pos2_2String "L_Pos2_2"
int L_Pos3_2;
#define L_Pos3_2String "L_Pos3_2"
int L_PositionToTarget;
#define L_PositionToTargetString "L_PositionToTarget"
int L_lockOnTokenName_2;
#define L_lockOnTokenName_2String "L_lockOnTokenName_2"
int L_isRelative_3;
#define L_isRelative_3String "L_isRelative_3"
int L_Pos1_3;
#define L_Pos1_3String "L_Pos1_3"
int L_Pos2_3;
#define L_Pos2_3String "L_Pos2_3"
int L_Pos3_3;
#define L_Pos3_3String "L_Pos3_3"
int L_Restart;
#define L_RestartString "L_Restart"
int L_ShutDown;
#define L_ShutDownString "L_ShutDown"
int L_StopMove;
#define L_StopMoveString "L_StopMove"
int L_AddPoint;
#define L_AddPointString "L_AddPoint"
int L_AddPointFromMeasurement;
#define L_AddPointFromMeasurementString "L_AddPointFromMeasurement"
int L_SetRotaionX;
#define L_SetRotaionXString "L_SetRotaionX"
int L_ValueInBaseUnits_53;
#define L_ValueInBaseUnits_53String "L_ValueInBaseUnits_53"
int L_AccuracyInBaseUnits;
#define L_AccuracyInBaseUnitsString "L_AccuracyInBaseUnits"
int L_SetRotaionY;
#define L_SetRotaionYString "L_SetRotaionY"
int L_ValueInBaseUnits_54;
#define L_ValueInBaseUnits_54String "L_ValueInBaseUnits_54"
int L_AccuracyInBaseUnits_1;
#define L_AccuracyInBaseUnits_1String "L_AccuracyInBaseUnits_1"
int L_SetRotaionZ;
#define L_SetRotaionZString "L_SetRotaionZ"
int L_ValueInBaseUnits_55;
#define L_ValueInBaseUnits_55String "L_ValueInBaseUnits_55"
int L_AccuracyInBaseUnits_2;
#define L_AccuracyInBaseUnits_2String "L_AccuracyInBaseUnits_2"
int L_SetTranslationX;
#define L_SetTranslationXString "L_SetTranslationX"
int L_ValueInBaseUnits_56;
#define L_ValueInBaseUnits_56String "L_ValueInBaseUnits_56"
int L_AccuracyInBaseUnits_3;
#define L_AccuracyInBaseUnits_3String "L_AccuracyInBaseUnits_3"
int L_SetTranslationY;
#define L_SetTranslationYString "L_SetTranslationY"
int L_ValueInBaseUnits_57;
#define L_ValueInBaseUnits_57String "L_ValueInBaseUnits_57"
int L_AccuracyInBaseUnits_4;
#define L_AccuracyInBaseUnits_4String "L_AccuracyInBaseUnits_4"
int L_SetTranslationZ;
#define L_SetTranslationZString "L_SetTranslationZ"
int L_ValueInBaseUnits_58;
#define L_ValueInBaseUnits_58String "L_ValueInBaseUnits_58"
int L_AccuracyInBaseUnits_5;
#define L_AccuracyInBaseUnits_5String "L_AccuracyInBaseUnits_5"
int L_CalculateOrientation;
#define L_CalculateOrientationString "L_CalculateOrientation"
