#!/bin/bash
echo ON

export EPICS_APP=$(cd "$(dirname "$BASH_SOURCE")"; cd -P "$(dirname "$(readlink "$BASH_SOURCE" || echo .)")"; pwd)
export EPICS_APP_UI_DIR=${EPICS_APP}/8idtrackerApp/op/bob
#export DEFAULT_UI_FILE=${1:-${DEFAULT_UI_FILE:-ioc_motors.bob}}
export DEFAULT_UI_FILE=${1:-${DEFAULT_UI_FILE:-newDisplay.bob}}
export UI_FILE_MACROS=${2:-"P=8idtracker:"}
export R=LT1:

# #######################################
# # optional: support for PVs with large data sizes, such as areaDetector
# # This should agree with the environment variable set by the ioc
# # see 'putenv "EPICS_CA_MAX_ARRAY_BYTES=64008"' in iocBoot/ioc<target>/st.cmd

if [ "" == "${EPICS_CA_MAX_ARRAY_BYTES}" ]; then
  #export EPICS_CA_MAX_ARRAY_BYTES=64008
  export EPICS_CA_MAX_ARRAY_BYTES=8000100
fi

export START_PUTRECORDER=${EPICS_APP}/start_putrecorder
export MACROS_PY=${EPICS_APP_UI_DIR}/../python/macros.py
export EDITOR=nedit

#######################################
# start CSS-phoebus


#/APSshare/bin/phoebus -layout $EPICS_APP/phoebus.layout -resource "file:${EPICS_APP_UI_DIR}/${DEFAULT_UI_FILE}?${UI_FILE_MACROS}&target=window"
/net/s8iddserv/xorApps/epics/synApps_6_3/support/phoebus-4.7.3-SNAPSHOT/phoebus.sh -layout $EPICS_APP/phoebus.layout -resource "file:${EPICS_APP_UI_DIR}/${DEFAULT_UI_FILE}?${UI_FILE_MACROS}&target=window" 


